language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install flake8 pytest
  - pip install -r requirements.txt
before_script:
  - flake8 . --count --max-complexity=11 --max-line-length=85 --show-source --statistics
script:
  - pytest --capture=sys
after_success:
  - coveralls 
