language: python
dist: xenial  # required for Python >= 3.7 on Travis CI

python:
  - "2.7"
  - "3.6"
  - "3.7"

services:
  - mongodb

install:
  - pip install codecov flake8 pytest
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

before_script:
  - flake8 . --count --max-complexity=16 --show-source --statistics

script:
  - python -m app.server > /dev/null &
  - pytest --cov=./
  - kill $(lsof -t -i:7001)

after_success:
  - bash <(curl -s https://codecov.io/bash)
