language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - flake8 . --count --max-complexity=11 --max-line-length=150 --show-source --statistics
script:
  - echo success
after_success:
  - coveralls 
