language: python
python:
 - 2.7
 - 3.6
install:
 - pip install flake8
 - pip install -r requirements.txt
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - time flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - echo success
#  - py.test app/rss-generator.py
#  - py.test --cov
after_success: 
 - coveralls 
